version: "3"

services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www
    ports:
      - ${WEB_PORT}:80
    container_name: ${PHP_CONTAINER}

  mysql:
    image: mariadb:10.5
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
    container_name: ${MYSQL_CONTAINER}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASS}
    links:
      - mysql
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    container_name: ${PMA_CONTAINER}
